### ISSUE TITLE
In two-monitor setup, the wallpaperswitch works only on one of the monitors.

### ISSUE THREAD

**Issue by D-Johann** [martenjj/wallpaperswitch#16] opened 2019-06-08 00:03 UTC
My PC runs Linux Mint 18.3 KDE "Sylvia" operating system, which has KDE Plasma 5. Upon folowing the instructions on https://github.com/martenjj/wallpaperswitch (including those in README.kubuntu file - important!) to the letter, the wallpaperswitch installed smoothly. Thank you very much indeed.

There is one particular issue here that might be of interest to the develper(s) of this highly useful project. 

My system uses two monitors (the usual setup), call them "the left" (L) and "the right" (R) one. Thus, when one sets (say) 4 virtual Desktops, one gets a total of 8 "workspaces" - two visible at any one time - the left one and the right one - Lk and Rk (k = 1,2,3,4).

But the installation of "wallpaperswitch" appears possible either *only* for the "left" workspaces, or, *only* for the "right" workspaces. 

Say, the wallpaperswitch is configured for the "left" workspaces. Switching through virtual desktops k = 1,2,3,4 one then gets four different pictures displayed on the left monitor - but the right monitor always displays *the same* background picture (configured in the ordinary way, without the wallpaperswitch)!  
(The analogous happens when one configures wallpaperswitch for the "right" workspaces: then the right monitor cycles through four different pictures but the left monitor picture stays the same.)

Is there any way to modify the wallpaperswitch software so that, in the above example, one can have eight different background pictures, Lk, Rk (k=1,2,3,4)? (BTW: this too was a native property of KDE prior to "Plasma 5".)

**Comment by martenjj** [comment] 2019-09-29 15:35
Duplicate of #8.

**Closed as completed by martenjj** 2019-09-29 15:35 UTC
