### ISSUE TITLE
Log Spamming

### ISSUE THREAD

**Issue by jsamyth** [martenjj/wallpaperswitch#3] opened 2017-01-08 20:23 UTC
Leaving the default The "Background colour" and "Change every" settings in Plasma desktop settings can lead to log spamming with messages similar to:

`plasmashell[8880]: No metadata file in the package, expected it at: "/home/-user-/Pictures/"`

The default interval for "change every" is 10 seconds, and the above message will appear (multiple times) in the logs every 10 seconds..  It will also appear multiple times every time you switch desktops, but that is far less than every ten seconds.

I set the "Change Every" to 24 hours just to keep the logs cleaner.

This appears to be a case of the usual KDE/Plasma message spew, and nothing to do with wallpaperswitcher.

**Comment by martenjj** [comment] 2017-01-09 11:21
Duplicate of #2

**Closed as completed by martenjj** 2017-01-09 11:21 UTC
